---
- name: >
    Debian | set_fact
      mysql_supported_os: True
  set_fact:
    mysql_supported_os: True

- name: Debian | install packages
  apt: pkg={{ item }} state=installed
  with_items: mysql_packages

- name: Debian | configure the service
  template: src=Debian-my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify: restart mysql
